config/routes.rb
Brobasket::Application.routes.draw do
  
  resources :baskets

  root :to => 'pages#home'
  get 'home' => 'pages#home'

end

app/models/basket.rb
class Basket < ActiveRecord::Base
  attr_accessible :description, :ingredients, :name, :price, :image_1, :image_2, :image_3
  has_attached_file :image_1, styles: { medium: "100%"}
  has_attached_file :image_2, styles: { medium: "100%"}
  has_attached_file :image_3, styles: { medium: "100%"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  # GET /baskets
  # GET /baskets.json
  def index
    @baskets = Basket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @baskets }
    end
  end

  # GET /baskets/1
  # GET /baskets/1.json
  def show
    @basket = Basket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @basket }
    end
  end

  # GET /baskets/new
  # GET /baskets/new.json
  def new
    @basket = Basket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @basket }
    end
  end

  # GET /baskets/1/edit
  def edit
    @basket = Basket.find(params[:id])
  end

  # POST /baskets
  # POST /baskets.json
  def create
    @basket = Basket.new(params[:basket])

    respond_to do |format|
      if @basket.save
        format.html { redirect_to @basket, notice: 'Basket was successfully created.' }
        format.json { render json: @basket, status: :created, location: @basket }
      else
        format.html { render action: "new" }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /baskets/1
  # PUT /baskets/1.json
  def update
    @basket = Basket.find(params[:id])

    respond_to do |format|
      if @basket.update_attributes(params[:basket])
        format.html { redirect_to @basket, notice: 'Basket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baskets/1
  # DELETE /baskets/1.json
  def destroy
    @basket = Basket.find(params[:id])
    @basket.destroy

    respond_to do |format|
      format.html { redirect_to baskets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/baskets/_basket.html.erb
   <tr>
        <td><%= basket.name %></td>
        <td><%= basket.description %></td>
        <td><%= basket.ingredients %></td>
        <td><%= basket.price %></td>
        <td><%= image_tag basket.image_1(:medium), :style => "width: 20px" %></td>
        <td><%= link_to 'Show', basket %></td>
        <td><%= link_to 'Edit', edit_basket_path(basket) %></td>
        <td><%= link_to 'Destroy', basket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>

app/views/baskets/_form.html.erb
<%= simple_form_for(@basket, html: { class: "form-horizontal"}) do |f| %>
<%= f.error_notification %>
<%= f.input :name %>
<%= f.input :description, as: :text, input_html: { rows: "3" } %>
<%= f.input :ingredients %>
<%= f.number_field :price, :class => 'text_field', :step => 'any' %>
<%= f.input :image_1, label: "Upload an image" %>
<%= f.input :image_2, label: "Upload an image" %>
<%= f.input :image_3, label: "Upload an image" %>


<div class="form-actions">
	<%= f.button :submit, class: "btn btn-primary" %>
</div>
<% end %>

app/views/baskets/edit.html.erb
<h1>Editing basket</h1>

<%= render 'form' %>

<%= link_to 'Show', @basket %> |
<%= link_to 'Back', baskets_path %>

app/views/baskets/index.html.erb
<h1>Listing pins</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Ingredients</th>
                <th>Price</th>
                <th>Images</th>
            </tr>
        </thead>

        <tbody>
            <%= render @baskets %>
        </tbody>
    </table>

    <br />

    <%= link_to 'New Basket', new_basket_path %>

app/views/baskets/new.html.erb
<h1>New basket</h1>

<%= render 'form' %>

<%= link_to 'Back', baskets_path %>

app/views/baskets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @basket.name %>
</p>

<p>
  <b>Description:</b>
  <%= @basket.description %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency(@basket.price) %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @basket.ingredients %>
</p>


<%= link_to 'Edit', edit_basket_path(@basket) %> |
<%= link_to 'Back', baskets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brobasket</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>